"""init_products_categories

Revision ID: 1c2531ab573a
Revises:
Create Date: 2026-09-19 15:28:44.058754

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1c2531ab573a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column(
            "name", sa.String(), nullable=False, comment="Имя категории"
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Описание категории",
        ),
        sa.Column("parent_uuid", sa.UUID(), nullable=True),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.Column(
            "uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["parent_uuid"], ["categories.uuid"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_categories_uuid"), "categories", ["uuid"], unique=False
    )
    op.create_table(
        "outboxs",
        sa.Column(
            "event_type", sa.String(), nullable=False, comment="Тип события"
        ),
        sa.Column(
            "sent_at", sa.DateTime(), nullable=True, comment="Время отправки"
        ),
        sa.Column(
            "entity_id",
            sa.UUID(),
            nullable=False,
            comment="Уникальный айди сущности",
        ),
        sa.Column(
            "status",
            sa.Enum(
                "WAITING_FOR_SENDING",
                "SENT",
                "CREATED",
                "UNSENT",
                "ARCHIVED",
                name="event_status_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.Column(
            "uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_outboxs_entity_id"), "outboxs", ["entity_id"], unique=False
    )
    op.create_index(
        op.f("ix_outboxs_event_type"), "outboxs", ["event_type"], unique=False
    )
    op.create_index(op.f("ix_outboxs_uuid"), "outboxs", ["uuid"], unique=False)
    op.create_table(
        "products",
        sa.Column("name", sa.String(), nullable=False, comment="Имя продукта"),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Описание продукта",
        ),
        sa.Column("sku", sa.String(), nullable=False, comment="Код товара"),
        sa.Column(
            "price",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Стоимость  продукта",
        ),
        sa.Column(
            "currency", sa.String(length=3), nullable=False, comment="Валюта"
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Наличие продукта",
        ),
        sa.Column("category_uuid", sa.UUID(), nullable=False),
        sa.Column(
            "data",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="{}",
            nullable=False,
            comment="Дополнительные данные",
        ),
        sa.Column(
            "uuid", sa.UUID(), nullable=False, comment="Уникальный айди записи"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата создания",
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Дата обновления",
        ),
        sa.ForeignKeyConstraint(
            ["category_uuid"],
            ["categories.uuid"],
        ),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_products_sku"), "products", ["sku"], unique=True)
    op.create_index(
        op.f("ix_products_uuid"), "products", ["uuid"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_uuid"), table_name="products")
    op.drop_index(op.f("ix_products_sku"), table_name="products")
    op.drop_table("products")
    op.drop_index(op.f("ix_outboxs_uuid"), table_name="outboxs")
    op.drop_index(op.f("ix_outboxs_event_type"), table_name="outboxs")
    op.drop_index(op.f("ix_outboxs_entity_id"), table_name="outboxs")
    op.drop_table("outboxs")
    op.drop_index(op.f("ix_categories_uuid"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
